spring.application.name=gateway-service
server.port=8080

spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.mvc.routes[1].id=product-service
spring.cloud.gateway.mvc.routes[1].uri=http://product-service:8082
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/products/**

eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.instance.prefer-ip-address=true